### ISSUE TITLE
Output is broken

### ISSUE THREAD

**Issue by megapro17** [puddly/eac_logsigner#1]
So it throws me garbage like this:
`'\xff\xfeE\x00x\x00a\x00c\x00t\x00 \x00A\x00u\x00d\x00i\x00o\x00 \x00C\x00o\x00p\x00y\x00 \x00V\x001\x00.\x003\x00 \x00f\x00r\x00o\x00m\x00 \x002\x00.\x00 \x00S\x00e\x00p\x00t\x00e\x00m\x00b\x00e\x00r\x00 \x002\x000\x001\x006\x00\r\x00\n\x00\r\x00\n\x00E\x00A\x00C\x00 \x00e\x00x\x00t\x00r\x00a\x00c\x00t\x00i\x00o\x00n\x00 \x00l\x00o\x00g\x00f\x00i\x00l\x00e\x00 \x00f\x00r\x00o\x00m\x00 \x001\x008\x00.\x00 \x00J\x00u\x00n\x00e\x00 \x002\x000\x001\x008\x00,\x00 \x002\x003\x00:\x005\x004\x00\r\x00\n\x00\r\x00\n\x00p\x00e\x00o\x00p\x00l\x00e\x00 \x00/\x00 \x00c\x00h\x00r\x00i\x00s\x00t\x00m\x00a\x00s\x00\r\x00\n\x00\r\x00\n\x00U\x00s\x00e\x00d\x00 \x00d\x00r\x00i\x00v\x00e\x00 \x00 \x00:\x00 \x00H\x00L\x00-\x00D\x00T`

**Comment by puddly** [comment]
Can you attach the log file and what exactly you're running to get that output?
