### ISSUE TITLE
TypeError: '<=' not supported between instances of 'NoneType' and 'tuple'

### ISSUE THREAD

**Issue by searedvandal** [puddly/eac_logsigner#2]
When I try to run it I get this:

```bash
searedvandal-> python3.7 ~/eac_logsigner/eac.py --verify "White Noise - An Electric Storm.log" 
Traceback (most recent call last):
  File "/home/searedvandal/eac_logsigner/eac.py", line 167, in <module>
    elif version <= CHECKSUM_MIN_VERSION:
TypeError: '<=' not supported between instances of 'NoneType' and 'tuple'
```

Any idea on how to fix?

**Comment by puddly** [comment]
Can you attach (not paste) the log file?

**Comment by searedvandal** [comment]
[White Noise - An Electric Storm.log](https://github.com/puddly/eac_logsigner/files/2381656/White.Noise.-.An.Electric.Storm.log)

**Comment by puddly** [comment]
It's now fixed:

    $ python3 eac.py verify White.Noise.-.An.Electric.Storm.log
    White.Noise.-.An.Electric.Storm.log:  OK

**Comment by searedvandal** [comment]
Thanks a lot!
