### ISSUE TITLE
unexpected keyword argument 'required'

### ISSUE THREAD

**Issue by mweimholt** [puddly/eac_logsigner#4]
README.md says Python 3.6+, but running in Python 3.6.7 results in:

Traceback (most recent call last):
  File "eac.py", line 101, in <module>
    subparsers = parser.add_subparsers(dest='command', required=True)
  File "/usr/lib/python3.6/argparse.py", line 1716, in add_subparsers
    action = parsers_class(option_strings=[], **kwargs)
TypeError: __init__() got an unexpected keyword argument 'required'

The 'required' arg to add_subparsers [does not exist in Python 3.6](https://docs.python.org/3.6/library/argparse.html#argparse.ArgumentParser.add_subparsers). This appears to have been added in Python 3.7.

Consider changing README.md to say Python 3.7+.

**Comment by puddly** [comment]
I'll change that, thanks.

I started this project before Python 3.7 was released and have just been using the latest version when adding features.
