### ISSUE TITLE
CheckLog reports fine, eac_logsigner reports forged

### ISSUE THREAD

**Issue by anonyno** [puddly/eac_logsigner#5]
For the attached log, running `CheckLog.exe` returns "1. Log entry is fine!" but using `eac_logsigner` returns "Forged". Is this because `eac_logsigner` is more strict or is it a bug?

[Solo.log](https://github.com/puddly/eac_logsigner/files/5114589/Solo.log)

**Comment by anonyno** [comment]
It seems that your script wrongly assumes that EAC log files created at or before v1.0 beta 1 can't use a log checksum.

https://github.com/puddly/eac_logsigner/blob/2156dc0f1d4917923b051b15d1e44d540092c27a/eac.py#L10
https://github.com/puddly/eac_logsigner/blob/2156dc0f1d4917923b051b15d1e44d540092c27a/eac.py#L150

This is incorrect according to the website, which states the following in the [changelog for v1.0 beta 1](http://www.exactaudiocopy.de/en/index.php/resources/whats-new/whats-new/):

> \+ Option for writing a checksum over the extraction log data to the log file

**Comment by puddly** [comment]
Yeah, it's a bug. Changing `<=` to `<` should work but I need to rework the version number parser anyways so I'll fix this in a bit.

**Comment by puddly** [comment]
The fix works for me with your log file.

**Comment by anonyno** [comment]
I could be wrong but don't you want to change this to a `<` too?

https://github.com/puddly/eac_logsigner/blob/8d7acc049d58c597d54e2c34c457164c125d23b1/eac.py#L133

**Comment by puddly** [comment]
Thanks, fixed. I'll add unit tests to this project...eventually.
